server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/17613455373/microservicecloud-config.git #GitHub上git(https)仓库名字
          